# Corne Mini 3x5 - FACTORY TEST CONFIG
# Configuracao minima para teste de hardware

# Bluetooth
CONFIG_ZMK_KEYBOARD_NAME="Corne Test"
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
